name: Playwright Mobile Chrome Tests PROD

on:
  push:
    branches:
      - 'feature/dedicated-*'
    
env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_ENDPOINT: https://mamyito.testops.cloud/
  ALLURE_PROJECT_ID: 1
  ALLURE_RESULTS: "allure-results"
  ALLURE_LAUNCH_NAME: "Mobile Chrome - Dzienny raport testów automatycznych na środowisku PROD"
  GITHUB-TOKEN: ${{ secrets.ALLURE_GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dmytrotus/node22:playwright-allure
    env:
      URL: ${{ secrets.PROD_URL_SECRET }}
      APIURL: ${{ secrets.PROD_APIURL_SECRET }}
      EMAIL: ${{ secrets.EMAIL_SECRET }}
      PASSWORD: ${{ secrets.PASSWORD_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true

      - name: Install and configure allurectl using Github Actions
        uses: allure-framework/setup-allurectl@v1

      - name: Run Playwright tests for Mobile Chrome with Allure
        run: allurectl watch -- npx playwright test --max-failures=0 --project="Mobile Chrome" --grep "@ProdSmoke"
        env:
          CI: 'true'

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: allure-results/
          retention-days: 1

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean